# Generated by Django 4.2 on 2023-04-25 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0004_task_assignee_task_due_date_task_is_completed_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
